import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {FormsModule } from '@angular/forms';
//import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
 
import { ToastrModule } from 'ngx-toastr';

//routermodule used for setting up application level route
import { RouterModule, Routes } from '@angular/router';
// these occures by using ng g [component] statements
//autogenerated files
import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { BlogViewComponent } from './blog-view/blog-view.component';
import { BlogCreateComponent } from './blog-create/blog-create.component';
import { BlogEditComponent } from './blog-edit/blog-edit.component';
import { NotfoundComponent } from './notfound/notfound.component';
import { AboutComponent } from './about/about.component';
//import statement from service
import { BlogService } from './blog.service';
import { BlogHttpService } from './blog-http.service';

import { HttpClientModule, HttpClient } from '@angular/common/http';

//decorators in angular
@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    BlogViewComponent,
    BlogCreateComponent,
    BlogEditComponent,
    NotfoundComponent,
    AboutComponent, 
  ],
  imports: [ 
    BrowserModule,
    HttpClientModule,
    FormsModule,
    //BrowserAnimationsModule,
    BrowserAnimationsModule, // required animations module
    ToastrModule.forRoot(),
      
    
    RouterModule.forRoot([
     {path:'Home', component:HomeComponent},
     {path:"",redirectTo:"Home",pathMatch:"full"},
     {path:'about',component:AboutComponent},
     {path:'create', component:BlogCreateComponent},
     {path:'edit/:blogId', component:BlogEditComponent},
     {path:'blog/:blogId', component:BlogViewComponent},
     {path:'**', component:NotfoundComponent}
    ])

  ],
  providers: [BlogService,BlogHttpService],
  //it tells that bootstsrap had made changes to app component  
  bootstrap: [AppComponent]
})
export class AppModule { }
